### ISSUE TITLE
Response Invalid on LaunchRequest

### ISSUE THREAD

**Issue by nickatnight** [youngsoul/PyAlexa#2]
Any reason why the launch request would not be working? The lambda response in the service simulator keep telling the 'response is invalid'. My intents seem to be working fine. I followed your tutorial verbatim.

**Comment by youngsoul** [comment]
Hi Nick

Does your launch request method look like this:
`    def on_launchrequest(self, launch_request, session):
`

I did make a change since that video such that the method names that are dispatched for requests look like:

on_<requestname>  for example  LaunchRequest, looks for a method of name:  on_launchrequest.   If you are using the AudioPlayer API then requests like:
`AudioPlayer.PlaybackStarted` call a method of the form:  on_audioplayer_playbackstarted

if you run the create_alexa_handler.py that was installed with the package:
python create_alexa_handler.py  the started class that it creates should have the correct methods.

To see what I am calling look at the methods:
_handle_amazon_request
_handle_amazon_intent
where I convert the requests and intents into methods to call.

Please let me know if you still have problems and I will help you out.

**Comment by nickatnight** [comment]
Oh ok I think I see what happened, I didnt create the new handler script and I can tell you refactored it a bunch. Let me test real quick. Thanks for your quick response! :) I really like this library

**Comment by nickatnight** [comment]
Ok now I'm getting 'The remote endpoint could not be called, or the response it returned was invalid.' in the service simulator?

**Comment by nickatnight** [comment]
Hmmm ok...so the launch request works when I comment out like so:

<img width="576" alt="screen shot 2017-01-10 at 6 14 36 pm" src="https://cloud.githubusercontent.com/assets/8783431/21832556/c1e77e26-d760-11e6-91ef-cd3b89e1baa1.png">

But the intents so do not work for me.

**Comment by youngsoul** [comment]
good catch.... self.card_title is never defined in this version, and I agree, it should be method scope.  I am pushing an update now to make that change.

I will walk through a sample generation myself, and see what I run into.

**Comment by nickatnight** [comment]
Sweet awesome...a couple more things:

- I don't see you documented anything regarding slots?

- Is there support for module importing from sub directories, ie: from utilities.foo import bar? (I see we can add necessary files when running 'create_aws_lambda' script, but not sure how that works with dirs).

Thanks heaps!

**Comment by youngsoul** [comment]
I just updated the test app, and it worked.  you can find that here:

https://github.com/youngsoul/PyAlexaSkillTest

I will improve docs... thanks for the nudge.  In the base class you can do things like:

`_get_intent(intent_request)`
`_get_intent_name(intent_request)`
`_get_slot_value("slot name", intent_request)`
`_slot_exists("slot name", intent_request)`
`_is_intent("intent name", intent_request)`

as for sub directories/modules, yes you can include that.
one of my skills create_aws_lambda command line looks like:
create_aws_lambda.py -i "AlexaMetraHandler.py,main.py,routes/__init__.py,routes/bnsf_route.py"

notes the routes/file_name.py

it assumes directories are relative to where you runt he create_aws_lambda script.

this will create a deployments directory with a deployment_100.zip (101,102, etc ).  You should then just upload the zip file to AWS Lambda.

**Comment by nickatnight** [comment]
Ahhh that worked like a charm sir, much appreciated. Are you accepting PRs?

**Comment by youngsoul** [comment]
I am very accepting of a PR.   I appreciate your efforts to make it better.


Thank you

**Comment by youngsoul** [comment]
I assume I can close this one, correct?

**Comment by nickatnight** [comment]
Most definitely.
